# Generated by Django 3.2.9 on 2021-11-21 15:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='random_url',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
