# Generated by Django 3.2.9 on 2021-11-21 22:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20211122_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='random_url',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='آدرس اختصاصی'),
        ),
    ]
