# Generated by Django 3.2.9 on 2021-11-22 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0006_alter_profile_random_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام محصول')),
                ('price', models.IntegerField(verbose_name='قیمت محصول')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصول',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('presenter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='account.profile', verbose_name='معرف')),
                ('product', models.ManyToManyField(to='market.Product')),
            ],
            options={
                'verbose_name': 'سبد خرید',
                'verbose_name_plural': 'سبد خرید',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='account.profile', verbose_name='خریدار')),
            ],
            options={
                'verbose_name': 'خریدار',
                'verbose_name_plural': 'خریدار',
            },
        ),
    ]
