# Generated by Django 3.2.9 on 2021-11-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_alter_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(default=1, verbose_name='جمع کل'),
            preserve_default=False,
        ),
    ]
